### ISSUE TITLE
[Bug] Bootloader could not be installed

### ISSUE THREAD

**Issue by natioifhoop** [T-Systems-MMS/sectpmctl#28]
### Description

For newer Lenovo models everything works without problems.
If I try this for a Lenovo T580 notebook, an error message appears.

### Reproduction steps

Everything up to step 4 works without problems.
After step 5 "sudo sectpmctl boot install".
I get the following error message:

### Current Behavior

Platform is in Setup Mode
Assuming Secure Boot mode: clearmode
WARNING:esys:src/tss2-esys/api/Esys_CreateLoaded.c:368:Esys_CreateLoaded_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_CreateLoaded.c:129:Esys_CreateLoaded() Esys Finish ErrorCode (0x000b0143)
ERROR: Esys_CreateLoaded(0xB0143) - rmt:error(2.0): command code not supported
ERROR: Unable to run tpm2_create
Failed at 610: tpm2_create -Q -C "${PERSISTANT_OWNER_SRK_NODA}" -c db.ctx -g sha256 -a "fixedtpm|fixedparent|sensitivedataorigin|userwithauth|decrypt|sign|noda" -p "str:$(cat "${SECTPMCTL_KEYS}/db.pwd")" -u db.pub -r db.priv with error code 1

### Expected Behavior

Boot loader should be installed.

### Additional information

...

**Comment by heikemms** [comment]
Hi, 
thanks for your bugreport. 
To further investigate your issue, we need some more information.
Which OS are you using, which version of tpm2-tools and which version of openSSL?

And can you please provide the output of following commands:

`sudo tpm2_getcap commands` 
if you want, you can just grep for `TPM2_CC_CreateLoaded`

**Comment by natioifhoop** [comment]
OS: Ubuntu 22.04.1

TPM2:  tpm2 --version
tool="tpm2" version="5.2" tctis="libtss2-tctildr" tcti-default=tcti-device

OpenSSL: OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

when i grep for 'TPM2_CC_CreateLoaded' there is no output.

[tpm2_getcap.zip](https://github.com/T-Systems-MMS/sectpmctl/files/10499853/tpm2_getcap.zip)

**Comment by natioifhoop** [comment]
Thanks for the quick reply!
Works without problems now
